"""empty message

Revision ID: 10fb8df5e7ae
Revises: 75b93fd83af6
Create Date: 2025-06-06 09:58:36.723124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10fb8df5e7ae'
down_revision = '75b93fd83af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Newarrivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('sizes', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('style', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.alter_column('main_image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('Thumb_One',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('Thumb_Two',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('Thumb_Three',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.alter_column('Thumb_Three',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('Thumb_Two',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('Thumb_One',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('main_image',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('Newarrivals')
    # ### end Alembic commands ###
