"""empty message

Revision ID: 3b787c35a1d7
Revises: e141107360d4
Create Date: 2025-06-07 00:34:52.951454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b787c35a1d7'
down_revision = 'e141107360d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Thumb_Four', sa.String(length=1000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.drop_column('Thumb_Four')

    # ### end Alembic commands ###
