"""Initial migration

Revision ID: 46d2a4c4c02f
Revises: 6967682f1640
Create Date: 2025-05-19 23:40:08.100484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d2a4c4c02f'
down_revision = '6967682f1640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Shoes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('main_image', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Thumb_One', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Thumb_Two', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Thumb_Three', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Shoes_pkey')
    )
    op.drop_table('product')
    # ### end Alembic commands ###
