"""empty message

Revision ID: 470e6b1aa897
Revises: 
Create Date: 2025-05-26 11:44:37.791317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470e6b1aa897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('sizes', sa.Numeric(precision=10), nullable=False),
    sa.Column('model', sa.String(length=10), nullable=False),
    sa.Column('style', sa.String(length=10), nullable=False),
    sa.Column('brand', sa.String(length=10), nullable=False),
    sa.Column('image_url', sa.String(length=10), nullable=False),
    sa.Column('main_image', sa.String(length=50), nullable=False),
    sa.Column('Thumb_One', sa.String(length=50), nullable=False),
    sa.Column('Thumb_Two', sa.String(length=50), nullable=False),
    sa.Column('Thumb_Three', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Shoes')
    # ### end Alembic commands ###
