"""empty message

Revision ID: 6967682f1640
Revises: 
Create Date: 2025-05-16 10:42:50.252522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6967682f1640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('main_image', sa.String(length=50), nullable=False),
    sa.Column('Thumb_One', sa.String(length=50), nullable=False),
    sa.Column('Thumb_Two', sa.String(length=50), nullable=False),
    sa.Column('Thumb_Three', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Shoes')
    # ### end Alembic commands ###
