"""empty message

Revision ID: 80062c2296d5
Revises: 470e6b1aa897
Create Date: 2025-05-26 11:49:20.764397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80062c2296d5'
down_revision = '470e6b1aa897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.alter_column('sizes',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.alter_column('sizes',
               existing_type=sa.String(length=10),
               type_=sa.NUMERIC(precision=10, scale=0),
               existing_nullable=False)

    # ### end Alembic commands ###
