"""empty message

Revision ID: e141107360d4
Revises: 10fb8df5e7ae
Create Date: 2025-06-07 00:30:26.072216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e141107360d4'
down_revision = '10fb8df5e7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.drop_column('main_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
